### PR TITLE
Make sublabels smaller on pad buttons

### LINKED ISSUE #136: Let dialer to rotate
Dialer and Clock are the two apps left to be locked in portrait mode.
Core apps at least should be able to be used in any orientation

### PR DESCRIPTION
**Pull request by cibersheep**
Make key button on dialer pad smaller for small screens or hide them (very small screens)

Fixes #136 and #6 

Needs to be tested on real device first

### CODE REVIEW

**Comment by cibersheep** [comment]
On Arale. Need to be tested on E4.5 with 2 SIM cards

Sublabels will adapt depending on the space left on the keypad

image

image

Or will hide if keypad is really small

**Comment by lduboeuf** [comment]
on BQ 4.5 landscape ( good on portrait ):
screenshot20201103_085300834

**Comment by cibersheep** [comment]
Thanks for testing <3 ... the user of #6 had two SIMs that makes the space even smaller (because of the Section element)

Aaaaand I'm not completely convinced about the vertical letters ¬¬ I may try another approach in the next days and see what goes better

**Comment by cibersheep** [comment]
Closed in favor of https://github.com/ubports/dialer-app/pull/140

**Pull request closed without merging**
