### PR TITLE
contact search with dial pad

### LINKED ISSUE #98: Dial pad autocomplete (feature suggestion)
It would be nice to have this kind of optional functionality in the UT dialer app: When you want to call e.g. "Salvatore" type the numbers corresponding to the letters in his name in the right order (S → 7, A → 2, L → 5, ...). The app will then suggest at max 3 contacts (sorted alphabetically). Once the right contact appears you can select his/her name, the phone number will be passed to the keypad entry field and you are ready to call.

**A very simple dial pad autocomplete:**

->Demo gif<-

### PR DESCRIPTION
**Pull request by lduboeuf**
fixes #98

From the idea of hendrikscheewel. We search for firstname or lastname (starting with). If no contacts found with letters then try with phone numbers. Favorites when fetched are shown first
We can disable/enable this feature in settings 

This is the continuation of previous PR: 
https://github.com/ubports/dialer-app/pull/142 and reverted by https://github.com/ubports/dialer-app/pull/152
 rewritten in c++ due to performance issues
~~https://github.com/ubports/telephony-service/pull/29 needs to be merged to have the full implementation~~

screenshot20210331_162112761
screenshot20210331_161904799

Click package for test:
see https://github.com/lduboeuf/dialer-app/actions , check for last build and choose artefact

TODO:
~~contacts without phone numbers shouldn't be displayed~~

### CODE REVIEW

**Comment by lduboeuf** [comment]
i'm struggling with :
tests/qml/tst_QmlTests': double free or corruption (out): 0x00007f27cc00b380 ***


I've spotted the culprint here:
https://github.com/ubports/dialer-app/blob/48dfcb723fc76f11cb7b5dccbd6a3da821b2a2b7/src/dialpadsearch.cpp#L66
When removing that part, tests are fine:
`static i18n::phonenumbers::PhoneNumberUtil *phonenumberUtil =  i18n::phonenumbers::PhoneNumberUtil::GetInstance();`

Do i miss something ?
GetInstance() retrieve a static pointer, i've tried not to using it in the class constructor, but same issue.
Where can i look for ?


EDIT: We can reproduce the error when running dialer-app, shutdown doesn't terminate well:
```
1  __GI_raise                                                 raise.c      54   0x7ffff52c9438 
2  __GI_abort                                                 abort.c      89   0x7ffff52cb03a 
3  __libc_message                                             libc_fatal.c 175  0x7ffff530b7fa 
4  malloc_printerr                                            malloc.c     5020 0x7ffff531438a 
5  _int_free                                                  malloc.c     3874 0x7ffff531438a 
6  __GI___libc_free                                           malloc.c     2975 0x7ffff531858c 
7  google::protobuf::internal::DestroyDefaultRepeatedFields()                   0x7fffdad403d1 
8  google::protobuf::ShutdownProtobufLibrary()                                  0x7ffff490a6cb 
9  ??                                                                           0x7fffdb41a3e9 
10 _dl_fini                                                   dl-fini.c    235  0x7ffff7de7e27 
11 __run_exit_handlers                                        exit.c       82   0x7ffff52ce008 
12 __GI_exit                                                  exit.c       104  0x7ffff52ce055 
13 __libc_start_main                                          libc-start.c 325  0x7ffff52b4847 
14 _start                                                                       0x415359       

So there could be an issue with ProtoBuff that PhoneNumberUtil rely on

**Comment by lduboeuf** [comment]
after some investigations, it seems that there is a known issue with the protobuf shutdown method. So maybe i should wait for focal and possible protobuff/libphonenumber upgrade

**Comment by lduboeuf** [comment]
finally moved the i18n::phonenumbers::PhoneNumberUtil to PhoneUtils in Telephony-service,

**Comment by lduboeuf** [comment]
~~need to exclude contacts without phone numbers~~

**Comment by lduboeuf** [comment]
need to keep sort order for favorites too

**Comment by lduboeuf** [comment]
oh i need to squash commits

**Comment by Flohack74** [comment]
I like the feature flag here: Its a safe way to introduce bigger features, and in the same time let the user have an option to bailout again,
Major web services do the same. I really propose to do this more often, our feature branches otherwise fall behind, get hard to maintain etc. And you also get only user feedback when its already aus.

**Comment by lduboeuf** [comment]
@Flohack74 thx!. Waiting impatiently to be merged now ;-)

**Comment by lduboeuf** [comment]
wait for new contact backend

**Comment by lduboeuf** [comment]
This revision is compatible with the new backend version. Will only need to change the manager when ready: https://github.com/ubports/dialer-app/pull/158/files#diff-efc206a97f970f7e5fe0927eefe57add4c1397db3267581974e0292c2076d9a7R76

**Review by Flohack74 — APPROVED** [review]

**Pull request merged**
