### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by ubports-weblate**
Translations update from [Weblate](https://translate.ubports.com/projects/ubports/dialer-app/) for UBports/dialer-app.

### CODE REVIEW

**Comment by peat-psuwit** [comment]
Don't know a thing about German, but this feels off. @Flohack74 could you please have a look? The Weblate page for the word is:
https://translate.ubports.com/translate/ubports/dialer-app/de/?q=Off&checksum=&offset=#history

**Comment by Flohack74** [comment]
Its just lowercase of the previous word but probably should be still uppercase. I will see how to revert it.

**Comment by lduboeuf** [comment]
btw dialer-app pot in weblate is not synced with repository :)
But, if pending PR are merged it will need to be updated again...

**Review by Flohack74 — APPROVED** [review]

**Comment by Flohack74** [comment]
@peat-psuwit I talked with the translator and we reverted the change in German. @lduboeuf will take a look and push manually again.

**Comment by lduboeuf** [comment]
@Flohack74 what needs to be done ? I see pot file is still not updated in weblate

**Comment by Flohack74** [comment]
I need to log in to the machine, go to the underlying Git repo, manually update, then refresh all po files from pot then commit ;)
I will do it now

**Comment by Flohack74** [comment]
I am totally overworked these days...

**Pull request merged**
