### PR TITLE
activate search mode on load of ContactsPage.qml

### PR DESCRIPTION
**Pull request by balcy**
https://github.com/ubports/ubuntu-touch/issues/657
tried the change on BQ Aquaris 4.5 by setting it to read/write and changing the QML file directly (vivid)
should work for xenial as well, which I cannot test right now

### CODE REVIEW

**Review by mariogrip — APPROVED** [review]
LGTM

**Comment by NeoTheThird** [comment]
Thanks @balcy, good job!

@mariogrip @Flohack74 Please remember to close the corresponding issues so they are added to the QA column when merging PRs!

**Comment by Flohack74** [comment]
Sorry, missed it!

**Comment by balcy** [comment]
you're welcome, was just 1 line : )

**Pull request merged**
