### PR TITLE
activate search mode on load of ContactsPage.qml

### PR DESCRIPTION
**Pull request by balcy**
https://github.com/ubports/ubuntu-touch/issues/657
tried the change on BQ Aquaris 4.5 by setting it to read/write and changing the QML file directly (vivid)
should work for xenial as well, which I cannot test right now

### CODE REVIEW

**Comment by Flohack74** [comment]
Is this the same as in #34 ?
grafik

**Comment by jbruechert** [comment]
It's the same PR targeted at different branches, xenial and vivid.

**Comment by balcy** [comment]
yes the same change for xenial as for vivid, I was not sure if I should make the PR to vivid only (that could be merged to xenial) or to xenial directly, so I've made both  : )

**Comment by mariogrip** [comment]
There will be no more builds for vivid so the vivid braches are deprecated at this point. So I will close this one, and review the other target for xenial :)

**Pull request closed without merging**
