### PR TITLE
implement contact search with the dialpad

### LINKED ISSUE #98: Dial pad autocomplete (feature suggestion)
It would be nice to have this kind of optional functionality in the UT dialer app: When you want to call e.g. "Salvatore" type the numbers corresponding to the letters in his name in the right order (S → 7, A → 2, L → 5, ...). The app will then suggest at max 3 contacts (sorted alphabetically). Once the right contact appears you can select his/her name, the phone number will be passed to the keypad entry field and you are ready to call.

**A very simple dial pad autocomplete:**

->Demo gif<-

### PR DESCRIPTION
**Pull request by lduboeuf**
fixes https://github.com/ubports/dialer-app/issues/98

So from the idea of hendrikscheewel. We search for firstname or lastname (starting with). If no contacts found with letters then try with phone numbers

screenshot20201112_161836331

### CODE REVIEW

**Comment by lduboeuf** [comment]
so did an heavy try today by allowing to search with phone number if nothing found with letters, sadly it is not reliable.
I need to dig deeper.
So i will just add the search by letters feature for now

**Comment by lduboeuf** [comment]
phone numbers popup is too intrusive

**Comment by lduboeuf** [comment]
wait for landscape fix by @cibersheep before marked as review ready

**Comment by lduboeuf** [comment]
Reminder for me: check without UnionFilter

**Comment by lduboeuf** [comment]
humm somethings is broken, it don't behave correctly now, need to figure out why. Maybe my force push. idk
very strange, the deb that is now is outdated according to the code changelog.
I re-run a build
[Edit]: Something was not properly built, or i had the dialer-app opened while updating it. So no, it is back to ok!

**Review by mariogrip — APPROVED** [review]
LGTM :+1: 

Minor nitpick is that there so some extra newlines in src

**Comment by FlavioMala** [comment]
Mhhh... few days ago it worked with numbers without international prefix (e.g. +39).
With +xx, 4 numbers were needed after the prefix (nothing appears), then deleting the 4th one.
Example:
+39 (nothing happens)
+39 123 4 (nothing happens)
+39 123 (now "search" works).

But today it doesn't work anymore (disabled?)

**Comment by lduboeuf** [comment]
@FlavioMala yes i've decided to remove it from OTA-16 since it does not work well anymore, need to work on it later, see #151

**Comment by FlavioMala** [comment]
Ahh.. OK! "Pardon!"

(But when you come back to work on it, don't forget what I wrote about the 4th number -insert/delete- and the prefixes 00xx: it can be useful!)

**Pull request merged**
