### PR TITLE
provide start and quick call facility

### PR DESCRIPTION
**Pull request by lduboeuf**
This PR allow to call dialer-app with an argument to trigger a call directly.
It also add the ability to call directly someone by clicking on the "call" icon in the  contact view

### CODE REVIEW

**Review by Flohack74 — APPROVED** [review]

**Comment by ghost** [comment]
As said in [here](https://github.com/ubports/address-book-app/pull/123), it sadly doesn't work on FP2.
Edit : it works ! You really have to aim for the icon with your thumb (it sounds stupid, I know), but it works. Thank you !

**Comment by farkasdvd** [comment]
Device: bq e5
Image: 2020-W35/2

Works as expected.

**Comment by jezek** [comment]
There is a cal fo testing, how exactly test this? Should the call start by itself, or just the number gets filled out and you'll need to tap the call button?

**Comment by AppsLee** [comment]
Device: Nexus5
Image: 2020-W35/2

From the dial app, search a contact and tap on the phone icon, the call starts immediately.
From the dial app, from the recent calls, swipe left and tap the contact icon. On the contact page, tap the phone icon, the call starts immediately.
From the contact app, same behavior and it's fine for me.
From the recent calls, tap on the item, same behavior and still what I expect.

Everything's fine for me. The phone button is now faster. Taping the contact itself enter the phone number but the call is not made.

**Comment by farkasdvd** [comment]
Device: bq e5
Image: 2020-W35/2

Correcting my previous comment, I see different behavior than AppsLee.
For me the call starts immediately only when I press the phone button for one of my contacts in dialer-app.
The phone button in address-book-app only loads the phone number, the call doesn't start.
Tapping a recent or missed call in dialer-app also just loads the phone number.

**Comment by jezek** [comment]
Device: FP2
Image: 2020-W35/2

Works as @farkasdvd described.

I think @AppsLee meant the same as @farkasdvd in last two lines, just the chosen wording can be misinterpreted.

**Pull request merged**
