### PR TITLE
Button Colors to Match System

### LINKED ISSUE #74: airplane mode mode, both buttons orange
Airplaine mode -> try and make call -> dialog popups up with both buttons orange.

Buttons should be themed to design spec.

### PR DESCRIPTION
**Pull request by cibersheep**
Don't merge until I can test on a device

This should close #74

### CODE REVIEW

**Comment by cibersheep** [comment]
Current vs modified

Flight mode warning:

imatge

Close button:

imatge

Change default SIM:

imatge

Change all SIM associations (to be changed on the next commit):

imatge

**Comment by cibersheep** [comment]
Forgot to say it was ok to merge :)

**Comment by UniversalSuperBox** [comment]
It looks like the translations file will change with these changes though... It needs to be rebuilt. :innocent:

**Comment by cibersheep** [comment]
I didn't change any string just the colors... you know me... but I can try to do whateva' is needed ;)

**Comment by Flohack74** [comment]
He looked at the screenshots and there are diverging texts, so if you did not change text then maybe you did not compare the same dialogs?

**Comment by cibersheep** [comment]
Oops, true. In close buttons both Dialogs are made from the same base but the screenshots are from different messages. I didn't change any text, just the colors:

imatge

**Pull request merged**
